//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test11
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "КодЗ as \'Код З\'",
            "Дата as \'Дата\'",
            "Статус as \'Статус\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Контрагент as \'Контрагент\'",
            "Контрагент.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Сотрудник.Фамилия",
            "Контрагент.Фамилия"})]
    [AssociatedDetailViewAttribute("ЗаказE", "СоставЗаказа", "СоставЗаказаE", true, "", "Состав заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ЗаказE", "Контрагент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ЗаказL", new string[] {
            "КодЗ as \'Код З\'",
            "Дата as \'Дата\'",
            "Статус as \'Статус\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Контрагент.Фамилия as \'Фамилия\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗ;
        
        private System.DateTime fДата;
        
        private IIS.Test11.Статусы fСтатус;
        
        private IIS.Test11.Сотрудник fСотрудник;
        
        private IIS.Test11.Контрагент fКонтрагент;
        
        private IIS.Test11.DetailArrayOfСоставЗаказа fСоставЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Дата CustomAttributes)

        // *** End programmer edit section *** (Заказ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Дата Get start)

                // *** End programmer edit section *** (Заказ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заказ.Дата Get end)

                // *** End programmer edit section *** (Заказ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Дата Set start)

                // *** End programmer edit section *** (Заказ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заказ.Дата Set end)

                // *** End programmer edit section *** (Заказ.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.КодЗ CustomAttributes)

        // *** End programmer edit section *** (Заказ.КодЗ CustomAttributes)
        public virtual int КодЗ
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.КодЗ Get start)

                // *** End programmer edit section *** (Заказ.КодЗ Get start)
                int result = this.fКодЗ;
                // *** Start programmer edit section *** (Заказ.КодЗ Get end)

                // *** End programmer edit section *** (Заказ.КодЗ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.КодЗ Set start)

                // *** End programmer edit section *** (Заказ.КодЗ Set start)
                this.fКодЗ = value;
                // *** Start programmer edit section *** (Заказ.КодЗ Set end)

                // *** End programmer edit section *** (Заказ.КодЗ Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Статус CustomAttributes)

        // *** End programmer edit section *** (Заказ.Статус CustomAttributes)
        public virtual IIS.Test11.Статусы Статус
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Статус Get start)

                // *** End programmer edit section *** (Заказ.Статус Get start)
                IIS.Test11.Статусы result = this.fСтатус;
                // *** Start programmer edit section *** (Заказ.Статус Get end)

                // *** End programmer edit section *** (Заказ.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Статус Set start)

                // *** End programmer edit section *** (Заказ.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Заказ.Статус Set end)

                // *** End programmer edit section *** (Заказ.Статус Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Контрагент CustomAttributes)

        // *** End programmer edit section *** (Заказ.Контрагент CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагент"})]
        [NotNull()]
        public virtual IIS.Test11.Контрагент Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Контрагент Get start)

                // *** End programmer edit section *** (Заказ.Контрагент Get start)
                IIS.Test11.Контрагент result = this.fКонтрагент;
                // *** Start programmer edit section *** (Заказ.Контрагент Get end)

                // *** End programmer edit section *** (Заказ.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Контрагент Set start)

                // *** End programmer edit section *** (Заказ.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (Заказ.Контрагент Set end)

                // *** End programmer edit section *** (Заказ.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заказ.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Test11.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Get start)

                // *** End programmer edit section *** (Заказ.Сотрудник Get start)
                IIS.Test11.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заказ.Сотрудник Get end)

                // *** End programmer edit section *** (Заказ.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Set start)

                // *** End programmer edit section *** (Заказ.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заказ.Сотрудник Set end)

                // *** End programmer edit section *** (Заказ.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СоставЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.СоставЗаказа CustomAttributes)
        public virtual IIS.Test11.DetailArrayOfСоставЗаказа СоставЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Get start)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Get start)
                if ((this.fСоставЗаказа == null))
                {
                    this.fСоставЗаказа = new IIS.Test11.DetailArrayOfСоставЗаказа(this);
                }
                IIS.Test11.DetailArrayOfСоставЗаказа result = this.fСоставЗаказа;
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Get end)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Set start)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Set start)
                this.fСоставЗаказа = value;
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Set end)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Test11.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Test11.Заказ));
                }
            }
        }
    }
}
