//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test11
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав заказа.
    /// </summary>
    // *** Start programmer edit section *** (СоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (СоставЗаказа CustomAttributes)
    [AutoAltered()]
    [Caption("Состав заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставЗаказаE", new string[] {
            "Товары.Название",
            "Товары.ЦенаЗаЕд",
            "Количество",
            "Стоимость"})]
    public class СоставЗаказа : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private double fСтоимость;
        
        private IIS.Test11.Товары fТовары;
        
        private IIS.Test11.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (СоставЗаказа CustomMembers)

        // *** End programmer edit section *** (СоставЗаказа CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Количество CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Количество Get start)

                // *** End programmer edit section *** (СоставЗаказа.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СоставЗаказа.Количество Get end)

                // *** End programmer edit section *** (СоставЗаказа.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Количество Set start)

                // *** End programmer edit section *** (СоставЗаказа.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СоставЗаказа.Количество Set end)

                // *** End programmer edit section *** (СоставЗаказа.Количество Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Стоимость CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Стоимость Get start)

                // *** End programmer edit section *** (СоставЗаказа.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (СоставЗаказа.Стоимость Get end)

                // *** End programmer edit section *** (СоставЗаказа.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Стоимость Set start)

                // *** End programmer edit section *** (СоставЗаказа.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (СоставЗаказа.Стоимость Set end)

                // *** End programmer edit section *** (СоставЗаказа.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Состав заказа.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Товары CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Товары CustomAttributes)
        [PropertyStorage(new string[] {
                "Товары"})]
        [NotNull()]
        public virtual IIS.Test11.Товары Товары
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Товары Get start)

                // *** End programmer edit section *** (СоставЗаказа.Товары Get start)
                IIS.Test11.Товары result = this.fТовары;
                // *** Start programmer edit section *** (СоставЗаказа.Товары Get end)

                // *** End programmer edit section *** (СоставЗаказа.Товары Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Товары Set start)

                // *** End programmer edit section *** (СоставЗаказа.Товары Set start)
                this.fТовары = value;
                // *** Start programmer edit section *** (СоставЗаказа.Товары Set end)

                // *** End programmer edit section *** (СоставЗаказа.Товары Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Test11.Заказ.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Заказ CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Заказ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказ"})]
        public virtual IIS.Test11.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Get start)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Get start)
                IIS.Test11.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Get end)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Set start)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Set end)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставЗаказаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставЗаказаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставЗаказаE", typeof(IIS.Test11.СоставЗаказа));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставЗаказа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)
    public class DetailArrayOfСоставЗаказа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Test11.DetailArrayOfСоставЗаказа members)

        // *** End programmer edit section *** (IIS.Test11.DetailArrayOfСоставЗаказа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставЗаказа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставЗаказа.
        /// </summary>
        public DetailArrayOfСоставЗаказа(IIS.Test11.Заказ fЗаказ) : 
                base(typeof(СоставЗаказа), ((ICSSoft.STORMNET.DataObject)(fЗаказ)))
        {
        }
        
        public IIS.Test11.СоставЗаказа this[int index]
        {
            get
            {
                return ((IIS.Test11.СоставЗаказа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Test11.СоставЗаказа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
